import { Injectable } from '@angular/core';
import { Pais } from '../interfaces/pais';

@Injectable({
  providedIn: 'root',
})
export class PaisService {
  constructor() {
    console.warn('entra paises');
  }

  getPaises() {
    return this.pais;
  }

  private pais: Pais[] = [
    // {abreviatura: 'AD', nombre: 'Andorra'},
    // {abreviatura: 'AE', nombre: 'Emiratos Árabes Unidos'},
    // {abreviatura: 'AF', nombre: 'Afganistán'},
    // {abreviatura: 'AG', nombre: 'Antigua y Barbuda'},
    // {abreviatura: 'AI', nombre: 'Anguilla'},
    // {abreviatura: 'AL', nombre: 'Albania'},
    // {abreviatura: 'AM', nombre: 'Armenia'},
    // {abreviatura: 'AN', nombre: 'Antillas Holandesas'},
    // {abreviatura: 'AO', nombre: 'Angola'},
    // {abreviatura: 'AQ', nombre: 'Antártida'},
    // {abreviatura: 'AR', nombre: 'Argentina'},
    // {abreviatura: 'AS', nombre: 'Samoa Americana'},
    // {abreviatura: 'AT', nombre: 'Austria'},
    // {abreviatura: 'AU', nombre: 'Australia'},
    // {abreviatura: 'AW', nombre: 'Aruba'},
    // {abreviatura: 'AZ', nombre: 'Azerbayán'},
    // {abreviatura: 'BA', nombre: 'Bosnia-Herzegovina'},
    // {abreviatura: 'BB', nombre: 'Barbados'},
    // {abreviatura: 'BD', nombre: 'Bangladesh'},
    // {abreviatura: 'BE', nombre: 'Bélgica'},
    // {abreviatura: 'BF', nombre: 'Burkina Faso'},
    // {abreviatura: 'BG', nombre: 'Bulgaria'},
    // {abreviatura: 'BH', nombre: 'Bahrain'},
    // {abreviatura: 'BI', nombre: 'Burundi'},
    // {abreviatura: 'BJ', nombre: 'Benín'},
    // {abreviatura: 'BM', nombre: 'Islas Bermudas'},
    // {abreviatura: 'BN', nombre: 'Brunei Darussalam'},
    // {abreviatura: 'BO', nombre: 'Bolivia'},
    // {abreviatura: 'BR', nombre: 'Brasil'},
    // {abreviatura: 'BT', nombre: 'Bahamas'},
    // {abreviatura: 'BS', nombre: 'Bután'},
    // {abreviatura: 'BV', nombre: 'Islas Buvet'},
    // {abreviatura: 'BW', nombre: 'Botswana'},
    // {abreviatura: 'BY', nombre: 'Bielorrusia'},
    // {abreviatura: 'BZ', nombre: 'Belice'},
    // {abreviatura: 'CA', nombre: 'Canadá'},
    // {abreviatura: 'CC', nombre: 'Isla de Cocos'},
    // {abreviatura: 'CD', nombre: 'República Democrática del Congo'},
    // {abreviatura: 'CF', nombre: 'República Centroafricana'},
    // {abreviatura: 'CG', nombre: 'República del Congo'},
    // {abreviatura: 'CH', nombre: 'Suiza'},
    // {abreviatura: 'CI', nombre: 'Costa de marfil'},
    // {abreviatura: 'CK', nombre: 'Islas Cook'},
    { abreviatura: 'CL', nombre: 'Chile' },
    // {abreviatura: 'CM', nombre: 'Camerún'},
    // {abreviatura: 'CN', nombre: 'China'},
    { abreviatura: 'CO', nombre: 'Colombia' },
    { abreviatura: 'CR', nombre: 'Costa Rica' },
    // {abreviatura: 'CS', nombre: 'Checoslovaquia (antiguo país)'},
    // {abreviatura: 'CU', nombre: 'Cuba'},
    // {abreviatura: 'CV', nombre: 'Cabo Verde'},
    // {abreviatura: 'CX', nombre: 'Islas Christmas'},
    // {abreviatura: 'CY', nombre: 'Chipre'},
    // {abreviatura: 'CZ', nombre: 'República Checa'},
    // {abreviatura: 'DE', nombre: 'Alemania'},
    // {abreviatura: 'DJ', nombre: 'Djibouti'},
    // {abreviatura: 'DK', nombre: 'Dinamarca'},
    // {abreviatura: 'DM', nombre: 'Dominica'},
    // {abreviatura: 'DO', nombre: 'República Dominicana'},
    // {abreviatura: 'DZ', nombre: 'Argelia'},
    { abreviatura: 'EC', nombre: 'Ecuador' },
    // {abreviatura: 'EE', nombre: 'Estonia'},
    // {abreviatura: 'EG', nombre: 'Egipto'},
    // {abreviatura: 'EH', nombre: 'Sáhara Occidental'},
    // {abreviatura: 'ER', nombre: 'Eritrea'},
    // {abreviatura: 'ES', nombre: 'España'},
    // {abreviatura: 'ET', nombre: 'Etiopía'},
    // {abreviatura: 'FI', nombre: 'Finlandia'},
    // {abreviatura: 'FJ', nombre: 'Fiji '},
    // {abreviatura: 'FK', nombre: 'Islas Malvinas'},
    // {abreviatura: 'FM', nombre: 'Micronesia '},
    // {abreviatura: 'FO', nombre: 'Islas Feroe'},
    // {abreviatura: 'FR', nombre: 'Francia'},
    // {abreviatura: 'GA', nombre: 'Gabón'},
    // {abreviatura: 'GD', nombre: 'Granada'},
    // {abreviatura: 'GE', nombre: 'Georgia'},
    // {abreviatura: 'GF', nombre: 'Guyana Francesa'},
    // {abreviatura: 'GG', nombre: 'Guernsey'},
    // {abreviatura: 'GH', nombre: 'Ghana'},
    // {abreviatura: 'GI', nombre: 'Gibraltar'},
    // {abreviatura: 'GL', nombre: 'Groenlandia'},
    // {abreviatura: 'GM', nombre: 'Gambia'},
    // {abreviatura: 'GN', nombre: 'Guinea'},
    // {abreviatura: 'GP', nombre: 'Guadalupe'},
    // {abreviatura: 'GQ', nombre: 'Guinea Ecuatorial'},
    // {abreviatura: 'GR', nombre: 'Grecia'},
    // {abreviatura: 'GS', nombre: 'Islas Georgias y Sandwich del Sur'},
    { abreviatura: 'GT', nombre: 'Guatemala' },
    // {abreviatura: 'GU', nombre: 'Guam'},
    // {abreviatura: 'GW', nombre: 'Guinea-Bissau'},
    // {abreviatura: 'GY', nombre: 'Guayana'},
    // {abreviatura: 'HK', nombre: 'Hong Kong'},
    // {abreviatura: 'HM', nombre: 'Islas Heard y McDonald'},
    // {abreviatura: 'HN', nombre: 'Honduras'},
    // {abreviatura: 'HR', nombre: 'Croacia'},
    // {abreviatura: 'HT', nombre: 'Haití'},
    // {abreviatura: 'HU', nombre: 'Hungría'},
    // {abreviatura: 'ID', nombre: 'Indonesia'},
    // {abreviatura: 'IE', nombre: 'Irlanda'},
    // {abreviatura: 'IL', nombre: 'Israel'},
    // {abreviatura: 'IM', nombre: 'Isla de Man'},
    // {abreviatura: 'IN', nombre: 'India'},
    // {abreviatura: 'IO', nombre: 'Territorio británico del Océano Índico'},
    // {abreviatura: 'IQ', nombre: 'Iraq'},
    // {abreviatura: 'IR', nombre: 'Irán'},
    // {abreviatura: 'IS', nombre: 'Islandia'},
    // {abreviatura: 'IT', nombre: 'Italia'},
    // {abreviatura: 'JM', nombre: 'Jamaica'},
    // {abreviatura: 'JE', nombre: 'Jersey'},
    // {abreviatura: 'JO', nombre: 'Jordania'},
    // {abreviatura: 'JP', nombre: 'Japón'},
    // {abreviatura: 'KE', nombre: 'Kenia'},
    // {abreviatura: 'KG', nombre: 'Kyrgystán'},
    // {abreviatura: 'KH', nombre: 'Camboya'},
    // {abreviatura: 'KI', nombre: 'Kiribati'},
    // {abreviatura: 'KM', nombre: 'Islas Comores'},
    // {abreviatura: 'KN', nombre: 'San Kitts y Nevis'},
    // {abreviatura: 'KP', nombre: 'Corea del Norte'},
    // {abreviatura: 'KR', nombre: 'Corea del Sur'},
    // {abreviatura: 'KW', nombre: 'Kuwait'},
    // {abreviatura: 'KY', nombre: 'Islas Caimán'},
    // {abreviatura: 'KZ', nombre: 'Kazajistán'},
    // {abreviatura: 'LA', nombre: 'Laos'},
    // {abreviatura: 'LB', nombre: 'Líbano'},
    // {abreviatura: 'LC', nombre: 'Santa Lucía'},
    // {abreviatura: 'LI', nombre: 'Liechtenstein'},
    // {abreviatura: 'LK', nombre: 'Sri Lanka'},
    // {abreviatura: 'LR', nombre: 'Liberia'},
    // {abreviatura: 'LS', nombre: 'Lesoto'},
    // {abreviatura: 'LT', nombre: 'Lituania'},
    // {abreviatura: 'LU', nombre: 'Luxemburgo'},
    // {abreviatura: 'LV', nombre: 'Letonia'},
    // {abreviatura: 'LY', nombre: 'Libia'},
    // {abreviatura: 'MA', nombre: 'Marruecos'},
    // {abreviatura: 'MC', nombre: 'Mónaco'},
    // {abreviatura: 'MD', nombre: 'Moldavia'},
    // {abreviatura: 'MG', nombre: 'Madagascar'},
    // {abreviatura: 'MK', nombre: 'Macedonia'},
    // {abreviatura: 'MH', nombre: 'Islas Marshall'},
    // {abreviatura: 'ML', nombre: 'Mali '},
    // {abreviatura: 'MM', nombre: 'Birmania'},
    // {abreviatura: 'MN', nombre: 'Mongolia'},
    // {abreviatura: 'MO', nombre: 'Macao'},
    // {abreviatura: 'MP', nombre: 'Islas Marianas'},
    // {abreviatura: 'MQ', nombre: 'Martinica'},
    // {abreviatura: 'MR', nombre: 'Mauritania'},
    // {abreviatura: 'MS', nombre: 'Montserrat'},
    // {abreviatura: 'MT', nombre: 'Malta'},
    // {abreviatura: 'MU', nombre: 'Mauricio'},
    // {abreviatura: 'MV', nombre: 'Maldivas'},
    // {abreviatura: 'MW', nombre: 'Malawi'},
    { abreviatura: 'MX', nombre: 'México' },
    // {abreviatura: 'MY', nombre: 'Malasia'},
    // {abreviatura: 'MZ', nombre: 'Mozambique'},
    // {abreviatura: 'NA', nombre: 'Namibia'},
    // {abreviatura: 'NC', nombre: 'Nueva Caledonia'},
    // {abreviatura: 'NE', nombre: 'Níger'},
    // {abreviatura: 'NF', nombre: 'Islas Norfolk'},
    // {abreviatura: 'NG', nombre: 'Nigeria'},
    // {abreviatura: 'NI', nombre: 'Nicaragua'},
    // {abreviatura: 'NL', nombre: 'Países Bajos'},
    // {abreviatura: 'NO', nombre: 'Noruega'},
    // {abreviatura: 'NP', nombre: 'Nepal'},
    // {abreviatura: 'NR', nombre: 'Nauru'},
    // {abreviatura: 'NT', nombre: 'Zona Neutral'},
    // {abreviatura: 'NU', nombre: 'Niue'},
    // {abreviatura: 'NZ', nombre: 'Nueva Zelanda'},
    // {abreviatura: 'OM', nombre: 'Omán'},
    { abreviatura: 'PA', nombre: 'Panamá' },
    { abreviatura: 'PE', nombre: 'Perú' },
    // {abreviatura: 'PF', nombre: 'Polinesia Francesa'},
    // {abreviatura: 'PG', nombre: 'Papúa Nueva Guinea'},
    // {abreviatura: 'PH', nombre: 'Filipinas'},
    // {abreviatura: 'PK', nombre: 'Pakistán'},
    // {abreviatura: 'PL', nombre: 'Polonia'},
    // {abreviatura: 'PM', nombre: 'San Pedro y Miquelón'},
    // {abreviatura: 'PN', nombre: 'Pitcairn'},
    // {abreviatura: 'PR', nombre: 'Puerto Rico'},
    // {abreviatura: 'PS', nombre: 'Territorios Palestinos'},
    // {abreviatura: 'PT', nombre: 'Portugal'},
    // {abreviatura: 'PW', nombre: 'Palau'},
    { abreviatura: 'PY', nombre: 'Paraguay' },
    // {abreviatura: 'QA', nombre: 'Qatar'},
    // {abreviatura: 'RE', nombre: 'Isla Reunión'},
    // {abreviatura: 'RO', nombre: 'Rumanía'},
    // {abreviatura: 'RU', nombre: 'Rusia'},
    // {abreviatura: 'RW', nombre: 'Ruanda'},
    // {abreviatura: 'SA', nombre: 'Arabia Saudí'},
    // {abreviatura: 'SB', nombre: 'Islas Salomón'},
    // {abreviatura: 'SC', nombre: 'Islas Seychelles'},
    // {abreviatura: 'SD', nombre: 'Sudán'},
    // {abreviatura: 'SE', nombre: 'Suecia'},
    // {abreviatura: 'SG', nombre: 'Singapur'},
    // {abreviatura: 'SH', nombre: 'Santa Helena'},
    // {abreviatura: 'SI', nombre: 'Eslovenia'},
    // {abreviatura: 'SJ', nombre: 'Islas Svalbard y Jan Mayens'},
    // {abreviatura: 'SK', nombre: 'Eslovaquia'},
    // {abreviatura: 'SL', nombre: 'Sierra Leona'},
    // {abreviatura: 'SM', nombre: 'San Marino'},
    // {abreviatura: 'SN', nombre: 'Senegal'},
    // {abreviatura: 'SO', nombre: 'Somalia'},
    // {abreviatura: 'SR', nombre: 'Surinam'},
    // {abreviatura: 'SU', nombre: 'URSS'},
    // {abreviatura: 'ST', nombre: 'Santo Tomé y Príncipe'},
    { abreviatura: 'SV', nombre: 'El Salvador' },
    // {abreviatura: 'SY', nombre: 'Siria'},
    // {abreviatura: 'SZ', nombre: 'Suazilandia'},
    // {abreviatura: 'TC', nombre: 'Islas Turks y Caicos'},
    // {abreviatura: 'TD', nombre: 'Chad'},
    // {abreviatura: 'TF', nombre: 'Tierras Australes y Antárticas Francesas'},
    // {abreviatura: 'TG', nombre: 'Togo'},
    // {abreviatura: 'TH', nombre: 'Tailandia'},
    // {abreviatura: 'TJ', nombre: 'Tayikistán'},
    // {abreviatura: 'TK', nombre: 'Tokelau'},
    // {abreviatura: 'TM', nombre: 'Turkmenistán'},
    // {abreviatura: 'TN', nombre: 'Túnez'},
    // {abreviatura: 'TO', nombre: 'Tonga'},
    // {abreviatura: 'TP', nombre: 'Timor Oriental'},
    // {abreviatura: 'TR', nombre: 'Turquía'},
    // {abreviatura: 'TT', nombre: 'Trinidad y Tobago'},
    // {abreviatura: 'TV', nombre: 'Tuvalu'},
    // {abreviatura: 'TW', nombre: 'Taiwán'},
    // {abreviatura: 'TZ', nombre: 'Tanzania'},
    // {abreviatura: 'UA', nombre: 'Ucrania'},
    // {abreviatura: 'UG', nombre: 'Uganda'},
    // {abreviatura: 'UK', nombre: 'Reino Unido'},
    // {abreviatura: 'UM', nombre: 'Islas Ultramarinas de Estados Unidos '},
    { abreviatura: 'US', nombre: 'Estados Unidos de América' },
    { abreviatura: 'UY', nombre: 'Uruguay' },
    // {abreviatura: 'UZ', nombre: 'Uzbekistán'},
    // {abreviatura: 'VA', nombre: 'Vaticano'},
    // {abreviatura: 'VC', nombre: 'San Vicente y las Granadinas'},
    { abreviatura: 'VE', nombre: 'Venezuela' },
    // {abreviatura: 'VG', nombre: 'Islas Vírgenes Británicas'},
    // {abreviatura: 'VI', nombre: 'Islas Vírgenes Americanas'},
    // {abreviatura: 'VN', nombre: 'Vietnam'},
    // {abreviatura: 'VU', nombre: 'Vanuatu'},
    // {abreviatura: 'WF', nombre: 'Islas Wallis y Futuna'},
    // {abreviatura: 'WS', nombre: 'Samoa'},
    // {abreviatura: 'YE', nombre: 'Yemen'},
    // {abreviatura: 'YT', nombre: 'Mayotte'},
    // {abreviatura: 'YU', nombre: 'Yugoslavia (antiguo país)'},
    // {abreviatura: 'ZA', nombre: 'Sudáfrica'},
    // {abreviatura: 'ZM', nombre: 'Zambia'},
    // {abreviatura: 'ZR', nombre: 'Zaire (antiguo país)'},
    // {abreviatura: 'ZW', nombre: 'Zimbabwe'},
  ];
}
